### PR TITLE
Support returning None from get_location

### PR DESCRIPTION
**Pull request by taion**
This handles the case where created items are not retrievable, for whatever reason.

### CODE REVIEW

**Comment by itajaja** [comment]
ah, it happens that I actually needed this as well :)

Are you sure it actually works? doesn't `self.get_location(item)` throws if there is no GET?

**Comment by taion** [comment]
You can override it to return `None`.

**Comment by itajaja** [comment]
ah ok, so this just avoids an empty header. lgtm

**Comment by taion** [comment]
Flask special-cases the `Location` header, so without this you get something like `http://localhost/None` if you try to return `None`.

**Pull request merged**
