### PR TITLE
fix: Always return response data from assert_response

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by cancan101** [comment]
perhaps return `None` in the case of 204 ?

**Comment by taion** [comment]
I'm thinking `UNDEFINED` rather than `None`, perhaps.

**Comment by taion** [comment]
cc @yodaiken @itajaja what do we think?

**Comment by itajaja** [comment]
this makes sense. I think for 204 you shouldn't do anything special, but any other solution is fine

**Comment by taion** [comment]
to be clear, you mean the current impl of returning `UNDEFINED` when the response data are empty?

**Comment by itajaja** [comment]
correct, I mean, you shouldn't check `204` specifically

**Pull request merged**
