### PR TITLE
feat: return the updated item after update_item_raw

### PR DESCRIPTION
**Pull request by AaronBuxbaum**
This is more consistent, and compliant with the documentation

Screen Shot 2021-03-24 at 10 34 23 AM

### CODE REVIEW

**Review by sloria — APPROVED** [review]

**Comment by itajaja** [comment]
@sloria do you know what's the deal with test_shell failing?

**Comment by sloria** [comment]
Oy, I'm not sure..maybe an incompatibility with newer versions of SQLA on 3.6?

Sorry I'm booked up today so can't look into it closely.

As a stopgap you could just skip those tests on 3.6 and add a TODO ¯\_(ツ)_/¯

**Comment by jquense** [comment]
its versions not just 3.6, that's just the fastest one to fail here

**Comment by jquense** [comment]
it also seems to just be in the context of running via tox, running without that and they work fine

**Comment by jquense** [comment]
this is way over my head

**Comment by sloria** [comment]
Oh, I see. Looks like sqla 1.4 broke the shell command on all versions. Looking into this now.

**Comment by sloria** [comment]
All fixed; merging

**Pull request merged**
