### PR TITLE
feature: support custom json encoder

### PR DESCRIPTION
**Pull request by r1b**
This would save some typing in tests e.g when casting uuids.

### CODE REVIEW

**Comment by taion** [comment]
ah, what's the motivation here?

**Comment by r1b** [comment]
When sending request data that contains UUIDs I have to do `str(uuid)` or I get a JSONEncodeError

**Comment by itajaja** [comment]
that's usually what we do (stringifying the uuid) /shrug. I agree it's a little bit daunting

**Comment by taion** [comment]
I feel like I'd rather factor out parsers than add this to the view.

**Pull request closed without merging**
