### PR TITLE
[DON'T MERGE] check if item exists before creating missing

### PR DESCRIPTION
**Pull request by itajaja**
Just to start the conversation, would something like that make sense? If so I would add tests and make it better

### CODE REVIEW

**Comment by taion** [comment]
This really seems like a concern of the `authorization` to me.

**Comment by itajaja** [comment]
get_item is not using any authorization when creating the item though...

**Comment by itajaja** [comment]
Also, authorization doesn't actually know what's persisted on the database

**Comment by taion** [comment]
I know, but whether it's legal to create a missing item in this context seems like an auth concern.

**Pull request closed without merging**
