### PR TITLE
Allow setting with_for_update in update

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by taion** [comment]
we decided against it as a default thing in https://github.com/4Catalyzer/flask-resty/pull/91 given that most update operations are idempotent

**Comment by taion** [comment]
or idempotent is not the right term – "don't need locking" is more correct

**Comment by itajaja** [comment]
oops sorry, wanted to approve, but I merged 🤦‍♂️ gotta go to sleep

**Comment by taion** [comment]
same end result. thanks and have a good weekend!

**Pull request merged**
