### PR TITLE
style: use pre-commit, fourmat, and friends

### PR DESCRIPTION
**Pull request by sloria**
Only includes config and files generated by fourmat for now, to make this easier to review.

### CODE REVIEW

**Comment by taion** [comment]
I guess it's conventional to split up linting and testing?

**Comment by sloria** [comment]
> I guess it's conventional to split up linting and testing?

Yeah, makes individual tox envs run faster.

**Comment by sloria** [comment]
Bah, need to bump black version in fourmat to fix the trailing-comma feature detection.

Or maybe we should just drop py35 @taion ?

**Comment by taion** [comment]
Our last Python 3.5 users are the people using the TensorFlow Docker image that still ships 3.5 by default. I don't think any of those images are using Flask-RESTy any more, though.

I'd be fine with dropping Python 3.5 support for now. If it causes problems, we can always bump versions and add it back.

**Pull request merged**
