### PR TITLE
Upgrade for new apispec API

### PR DESCRIPTION
**Pull request by taion**

### CODE REVIEW

**Comment by itajaja** [comment]
ok!

**Comment by itajaja** [comment]
this should be enough? https://github.com/4Catalyzer/flask-resty-swagger/pull/5

I am using `0.18.2`, let me know if you want to cut a minor version instead

**Comment by taion** [comment]
This will v0.19.0.

**Comment by cancan101** [comment]
This now breaks usage of flask resty without `apispec` being installed (which is not listed in `setup.py`).
```
  File "/Users/alex/.pyenv/versions/app/lib/python3.7/site-packages/flask_resty/spec/__init__.py", line 9, in <module>
    from .plugin import FlaskRestyPlugin
  File "/Users/alex/.pyenv/versions/app/lib/python3.7/site-packages/flask_resty/spec/plugin.py", line 3, in <module>
    from apispec.ext.flask import FlaskPlugin
ModuleNotFoundError: No module named 'apispec'
```

**Pull request merged**
