### PR TITLE
improve sorting

### PR DESCRIPTION
**Pull request by itajaja**
I'll add tests when this looks good. This is not super flexible, as the fixed fields are only added in the end. The alternative would be to change the api to looks something like `Sorting('a', '-a', '+b')` where the one with +/- are fixed. bleah. other ideas?

Alternatively we can just move the ApiError check to `get_request_field_orderings` like in this PR, and this would help with easier subclassing

### CODE REVIEW

**Comment by itajaja** [comment]
see alternative at https://github.com/4Catalyzer/flask-resty/pull/170

**Comment by taion** [comment]
I don't understand why #170 is an alternative. Isn't it just a subset of this PR?

**Comment by taion** [comment]
I wonder if we could use something like:

```python
class IdSortingContainer(FieldSortingBase):
    def __init__(self, sorting):
        self._sorting = sorting

    def sort_query(self, query, view):
        query = self._sorting.sort_query(query, view)

        id_field_orderings = ((id_field, True) for id_field in view.id_fields)
        return self.sort_query_by_fields(query, view, id_field_orderings)

    def get_request_field_orderings(self):
        # TODO: Explicit tuple casts?
        return self._sorting.get_request_field_orderings() + foo  # ?? view
```

Not sure how exactly I want this API to look, but I think extending an existing sorting object to sort by ID fields is more like what we want.

**Comment by itajaja** [comment]
> I don't understand why #170 is an alternative. Isn't it just a subset of this PR?

That's correct. I just wanted to distinguish the two. I am not fond of this tho. I would propose to not add additional sorting classes in FR, and just allow more flexibility in userland

**Comment by itajaja** [comment]
kthxbye

**Pull request closed without merging**
