### PR TITLE
added get_deserializer to ColumnFilter

### PR DESCRIPTION
**Pull request by cancan101**
this allows subclasses to change how the deserializer is resolved

### CODE REVIEW

**Comment by itajaja** [comment]
what are you trying to achieve here? can't you just specify the specify deserializer in the subclass?

**Comment by itajaja** [comment]
maybe you could achieve the same thing by overriding `get_field`?

**Comment by cancan101** [comment]
@taion care to clarify?

**Comment by taion** [comment]
maybe we should just add a `schema=Foo` kwarg to `ColumnFilter`

**Comment by taion** [comment]
closing this out for now – the later proposals seem like a more targeted way to add this to the API

**Pull request closed without merging**
